### ISSUE TITLE
aspnetcore issue label consolidation

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/issue-labeler#17]
We're planning to carry out the plan in https://gist.github.com/JunTaoLuo/4e870ff12af55a0146ab3fbcf4bfd7e3.

**Comment by JunTaoLuo** [comment]
cc @maryamariyan 

TODOs:
- [ ] unblock labeling with a map of old labels to consolidated labels (short term fix)
- [ ] retrain model (long term fix)

**Comment by maryamariyan** [comment]
closing as resolved.
