### ISSUE TITLE
When labeling PRs with a linked issue, label could be copied from issue

### ISSUE THREAD

**Issue by ericstj** [dotnet/issue-labeler#2]
See PR https://github.com/dotnet/runtime/pull/38937

This is just a low-pri suggestion.

**Comment by maryamariyan** [comment]
More examples:

Taken from [github docs](https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#:~:text=issue%20will%20close.-,Closing%20an%20issue%20in%20the%20same%20repository,merged%20into%20the%20default%20branch).

- [ ] `Fixes #1`
- [ ] `Fix #1`
- [ ] `Fixed #1`
- [ ] `Resolves #1`
- [ ] `Resolve #1`
- [ ] `Resolved #1`
- [ ] `Closes #1`
- [ ] `Close #1`
- [ ] `Closed #1`
