### ISSUE TITLE
Auto-add Community tag to PRs?

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/issue-labeler#20]
It might be helpful if the Community tag were added automatically to PRs opened by users outside a certain group, e.g. those with permission to merge PRs. This is because the team needs to query such PRs periodically to make sure we're not letting our community contributors slip through the cracks.

This is probably not as relevant for issues, as there are many more community issues than PRs.

**Comment by Eilon** [comment]
I recommend using FabricBot to do this because this labeler is mostly about using ML to predict the most appropriate area for an issue or PR.

If you're not familiar with FabricBot, please contact me directly (easy to find me at Microsoft) and I can help you get set up!
