### ISSUE TITLE
Apply a `needs-area-label` label when no area can be identified

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/issue-labeler#27]
When the issue labeler is unable to determine which area label to apply to an issue, a comment is added to the issue, but no labels are applied. Because triage processes in large repositories are assigned by area, the issues that do not get an area label applied can slip through the cracks and not get triaged in a timely fashion.

GitHub issue search does not allow for a search of "all items that do not have a label starting with 'area-'". To work around that, very lengthy queries are needed that list out all of the area labels in a negated label search. For instance, the following queries can be used for dotnet/runtime and dotnet/dotnet-api-docs:

* [https://github.com/dotnet/runtime/issues?q=is%3Aopen+is%3Aissue+-label%3Aarea-AssemblyLoader-coreclr%2Carea-AssemblyLoader-mono%2Carea...](https://github.com/dotnet/runtime/issues?q=is%3Aopen+is%3Aissue+-label%3Aarea-AssemblyLoader-coreclr%2Carea-AssemblyLoader-mono%2Carea-Build-mono%2Carea-Codeflow%2Carea-Codegen-AOT-mono%2Carea-CodeGen-coreclr%2Carea-Codegen-Interpreter-mono%2Carea-Codegen-JIT-mono%2Carea-Codegen-LLVM-mono%2Carea-Codegen-meta-mono%2Carea-CoreLib-mono%2Carea-CrossGen%2FNGEN-coreclr%2Carea-crossgen2-coreclr%2Carea-Debugger-mono%2Carea-DependencyModel%2Carea-Diagnostics-coreclr%2Carea-EnC-mono%2Carea-ExceptionHandling-coreclr%2Carea-Extensions-Caching%2Carea-Extensions-Configuration%2Carea-Extensions-DependencyInjection%2Carea-Extensions-FileSystem%2Carea-Extensions-Hosting%2Carea-Extensions-HttpClientFactory%2Carea-Extensions-Logging%2Carea-Extensions-Options%2Carea-Extensions-Primitives%2Carea-GC-coreclr%2Carea-GC-mono%2Carea-Host%2Carea-HostModel%2Carea-ILTools-coreclr%2Carea-ILVerification%2Carea-Infrastructure%2Carea-Infrastructure-coreclr%2Carea-Infrastructure-installer%2Carea-Infrastructure-libraries%2Carea-Infrastructure-mono%2Carea-Interop-coreclr%2Carea-Interop-mono%2Carea-Meta%2Carea-Microsoft.CSharp%2Carea-Microsoft.Extensions%2Carea-Microsoft.VisualBasic%2Carea-Microsoft.Win32%2Carea-NativeAOT-coreclr%2Carea-PAL-coreclr%2Carea-PAL-libraries%2Carea-Performance-mono%2Carea-R2RDump-coreclr%2Carea-ReadyToRun-coreclr%2Carea-runtime%2Carea-Serialization%2Carea-Setup%2Carea-Single-File%2Carea-Snap%2Carea-System.Buffers%2Carea-System.CodeDom%2Carea-System.Collections%2Carea-System.ComponentModel%2Carea-System.ComponentModel.Composition%2Carea-System.ComponentModel.DataAnnotations%2Carea-System.Composition%2Carea-System.Configuration%2Carea-System.Console%2Carea-System.Data%2Carea-System.Data.Odbc%2Carea-System.Data.OleDB%2Carea-System.Data.SqlClient%2Carea-System.Diagnostics%2Carea-System.Diagnostics-coreclr%2Carea-System.Diagnostics-mono%2Carea-System.Diagnostics.Activity%2Carea-System.Diagnostics.EventLog%2Carea-System.Diagnostics.Metric%2Carea-System.Diagnostics.PerformanceCounter%2Carea-System.Diagnostics.Process%2Carea-System.Diagnostics.Tracing%2Carea-System.Diagnostics.TraceSource%2Carea-System.DirectoryServices%2Carea-System.Drawing%2Carea-System.Dynamic.Runtime%2Carea-System.Formats.Asn1%2Carea-System.Formats.Cbor%2Carea-System.Globalization%2Carea-System.IO%2Carea-System.IO.Compression%2Carea-System.IO.Pipelines%2Carea-System.Linq%2Carea-System.Linq.Expressions%2Carea-System.Linq.Parallel%2Carea-System.Management%2Carea-System.Memory%2Carea-System.Net%2Carea-System.Net.Http%2Carea-System.Net.Quic%2Carea-System.Net.Security%2Carea-System.Net.Sockets%2Carea-System.Numerics%2Carea-System.Numerics.Tensors%2Carea-System.Reflection%2Carea-System.Reflection-mono%2Carea-System.Reflection.Emit%2Carea-System.Reflection.Metadata%2Carea-System.Resources%2Carea-System.Runtime%2Carea-System.Runtime.Caching%2Carea-System.Runtime.CompilerServices%2Carea-System.Runtime.InteropServices%2Carea-System.Runtime.InteropServices.JavaScript%2Carea-System.Runtime.Intrinsics%2Carea-System.Security%2Carea-System.ServiceModel%2Carea-System.ServiceModel.Syndication%2Carea-System.ServiceProcess%2Carea-System.Speech%2Carea-System.Text.Encoding%2Carea-System.Text.Encodings.Web%2Carea-System.Text.Json%2Carea-System.Text.RegularExpressions%2Carea-System.Threading%2Carea-System.Threading.Channels%2Carea-System.Threading.Tasks%2Carea-System.Transactions%2Carea-System.Xml%2Carea-Threading-mono%2Carea-TieredCompilation-coreclr%2Carea-Tracing-coreclr%2Carea-Tracing-mono%2Carea-TypeSystem-coreclr%2Carea-UWP%2Carea-VM-coreclr%2Carea-VM-meta-mono)
* [https://github.com/dotnet/dotnet-api-docs/issues?q=is%3Aopen+is%3Aissue+-label%3Aarea-AssemblyLoader-coreclr%2Carea-AssemblyLoader-mono%2Carea...](https://github.com/dotnet/dotnet-api-docs/issues?q=is%3Aopen+is%3Aissue+-label%3Aarea-AssemblyLoader-coreclr%2Carea-AssemblyLoader-mono%2Carea-Build-mono%2Carea-Codeflow%2Carea-Codegen-AOT-mono%2Carea-CodeGen-coreclr%2Carea-Codegen-Interpreter-mono%2Carea-Codegen-JIT-mono%2Carea-Codegen-LLVM-mono%2Carea-Codegen-meta-mono%2Carea-CoreLib-mono%2Carea-CrossGen%2FNGEN-coreclr%2Carea-crossgen2-coreclr%2Carea-Debugger-mono%2Carea-DependencyModel%2Carea-Diagnostics-coreclr%2Carea-EnC-mono%2Carea-ExceptionHandling-coreclr%2Carea-Extensions-Caching%2Carea-Extensions-Configuration%2Carea-Extensions-DependencyInjection%2Carea-Extensions-FileSystem%2Carea-Extensions-Hosting%2Carea-Extensions-HttpClientFactory%2Carea-Extensions-Logging%2Carea-Extensions-Options%2Carea-Extensions-Primitives%2Carea-GC-coreclr%2Carea-GC-mono%2Carea-Host%2Carea-HostModel%2Carea-ILTools-coreclr%2Carea-ILVerification%2Carea-Infrastructure%2Carea-Infrastructure-coreclr%2Carea-Infrastructure-installer%2Carea-Infrastructure-libraries%2Carea-Infrastructure-mono%2Carea-Interop-coreclr%2Carea-Interop-mono%2Carea-Meta%2Carea-Microsoft.CSharp%2Carea-Microsoft.Extensions%2Carea-Microsoft.VisualBasic%2Carea-Microsoft.Win32%2Carea-NativeAOT-coreclr%2Carea-PAL-coreclr%2Carea-PAL-libraries%2Carea-Performance-mono%2Carea-R2RDump-coreclr%2Carea-ReadyToRun-coreclr%2Carea-runtime%2Carea-Serialization%2Carea-Setup%2Carea-Single-File%2Carea-Snap%2Carea-System.Buffers%2Carea-System.CodeDom%2Carea-System.Collections%2Carea-System.ComponentModel%2Carea-System.ComponentModel.Composition%2Carea-System.ComponentModel.DataAnnotations%2Carea-System.Composition%2Carea-System.Configuration%2Carea-System.Console%2Carea-System.Data%2Carea-System.Data.Odbc%2Carea-System.Data.OleDB%2Carea-System.Data.SqlClient%2Carea-System.Diagnostics%2Carea-System.Diagnostics-coreclr%2Carea-System.Diagnostics-mono%2Carea-System.Diagnostics.Activity%2Carea-System.Diagnostics.EventLog%2Carea-System.Diagnostics.Metric%2Carea-System.Diagnostics.PerformanceCounter%2Carea-System.Diagnostics.Process%2Carea-System.Diagnostics.Tracing%2Carea-System.Diagnostics.TraceSource%2Carea-System.DirectoryServices%2Carea-System.Drawing%2Carea-System.Dynamic.Runtime%2Carea-System.Formats.Asn1%2Carea-System.Formats.Cbor%2Carea-System.Globalization%2Carea-System.IO%2Carea-System.IO.Compression%2Carea-System.IO.Pipelines%2Carea-System.Linq%2Carea-System.Linq.Expressions%2Carea-System.Linq.Parallel%2Carea-System.Management%2Carea-System.Memory%2Carea-System.Net%2Carea-System.Net.Http%2Carea-System.Net.Quic%2Carea-System.Net.Security%2Carea-System.Net.Sockets%2Carea-System.Numerics%2Carea-System.Numerics.Tensors%2Carea-System.Reflection%2Carea-System.Reflection-mono%2Carea-System.Reflection.Emit%2Carea-System.Reflection.Metadata%2Carea-System.Resources%2Carea-System.Runtime%2Carea-System.Runtime.Caching%2Carea-System.Runtime.CompilerServices%2Carea-System.Runtime.InteropServices%2Carea-System.Runtime.InteropServices.JavaScript%2Carea-System.Runtime.Intrinsics%2Carea-System.Security%2Carea-System.ServiceModel%2Carea-System.ServiceModel.Syndication%2Carea-System.ServiceProcess%2Carea-System.Speech%2Carea-System.Text.Encoding%2Carea-System.Text.Encodings.Web%2Carea-System.Text.Json%2Carea-System.Text.RegularExpressions%2Carea-System.Threading%2Carea-System.Threading.Channels%2Carea-System.Threading.Tasks%2Carea-System.Transactions%2Carea-System.Xml%2Carea-Threading-mono%2Carea-TieredCompilation-coreclr%2Carea-Tracing-coreclr%2Carea-Tracing-mono%2Carea-TypeSystem-coreclr%2Carea-UWP%2Carea-VM-coreclr%2Carea-VM-meta-mono%2Carea-extensions-DiagnosticAdapter%2Carea-Extensions-Localization%2Carea-Extensions-Logging-AzureAppServices%2Carea-Extensions-ObjectPool%2Carea-msbuild%2Carea-NetStandard%2Carea-System.Device%2Carea-System.Web%2Carea-WASM%2Carea-WCF%2Carea-WF%2Carea-WFC%2Carea-WIF%2Carea-WinForms%2Carea-WPF%2Cdotnet-api/prod%2Cdotnet-csharp/prod%2Cdotnet-roslyn-api/prod+)

Searches can be done to find where the issue-labeler made comments indicating that no area label could be applied, but those searches still include items where an area label has since been applied.

* https://github.com/dotnet/runtime/issues?q=is%3Aissue+%22I+couldn%27t+figure+out+the+best+area+label+to+add+to+this+issue%22+is%3Aopen
* https://github.com/dotnet/dotnet-api-docs/issues?q=is%3Aissue+%22I+couldn%27t+figure+out+the+best+area+label+to+add+to+this+issue%22+is%3Aopen

To make this task of identifying and routing issues where no label could be applied more approachable, I recommend allowing the issue-labeler to have a default label to apply when no area label is applied. I recommend `needs-area-label` as the label name we'd use in dotnet/runtime and dotnet/dotnet-api-docs.

With a `needs-area-label` label applied, we would then be able to easily query for such issues and PRs, apply the appropriate area label, and remove the `needs-area-label` label. This capability would pair nicely with how we're using FabricBot to tag area owners and add issues to area owners' project boards for triage, improving our accountability for routing and triaging issues. In the dotnet/runtime and dotnet/dotnet-api-docs repository, @ericstj and @jeffhandley have this responsibility.

When the `needs-area-label` label is applied, the comment should be:

> I couldn't figure out the best area label to add to this issue; the `needs-area-label` label has been applied instead. If you have write-permissions please help me learn by adding exactly one area label and removing `needs-area-label`.

Tagging @marek-safar @jeffschwMSFT @danmoseley @gewarren @BillWagner for visibility.

**Comment by danmoseley** [comment]
Seems reasonable to me but it would probably have to be configurable as not all repos might want it

**Comment by gewarren** [comment]
Sounds good. It would be good if `needs-area-label` was automatically removed once one of the `area-` labels has been applied.

**Comment by jeffhandley** [comment]
> Sounds good. It would be good if `needs-area-label` was automatically removed once one of the `area-` labels has been applied.

Good idea. This could be handled in the FabricBot configuration.

**Comment by jeffhandley** [comment]
@ericstj brought up a good point:

> Any issue that has this label should be excluded from training

That will ensure we don't inadvertently train the bot to apply `needs-area-label`--but instead only apply it as the default/fallback (if the repo is opted into such a config).

**Comment by ericstj** [comment]
> Good idea. This could be handled in the FabricBot configuration.

It's not all that dissimilar from the action that users take when reassigning an area -- remove the previous area.

**Comment by jeffhandley** [comment]
Good point, Eric. We can hold off on automating that until we see a need to do so.

**Comment by maryamariyan** [comment]
Sounds good. I'll get to this on by end of next week.

**Comment by vcsjones** [comment]
To further expand on this, carrying some motivation from https://github.com/dotnet/runtime/issues/80296, I would also recommend removing (or having some option repositories can opt in to) the default comment when an area- label can't be determined.

This comment from the integration causes some confusion for people new to the repository, and ultimately leads to them several edits to put the label in the issue title, the body, or thinking something is not working correctly.

**Comment by jeffschwMSFT** [comment]
I am neutral on the proposal.  I am not sure if we have a great need here.  There are a few of us that keep the unlabeled issues under control (@vcsjones is one of them), I also do a fair share.  On a given day we likely have less than a dozen.  Though being neutral means also that I am not opposed.

**Comment by jeffhandley** [comment]
As the team members accountable for `area-Meta` triage, @ericstj and I consider ourselves accountable for issues with no label as well. We've greatly appreciated that @jeffschwMSFT, @vcsjones, and many others have contributed to keeping it clean! Nonetheless, we'd benefit from being able to _query_ for such issues easily. I also appreciate @vcsjones's point that the comment itself can cause confusion.

Those aspects have me leaning toward moving this forward as something repos can configure.

**Comment by jeffhandley** [comment]
This is now fixed and deployed via #53.

The `dispatcher-app` now supports configuration of `{owner}:{repo}:no_area_determined_label` where the value of that setting is the label to apply to issues where no area label could be determined. When the label is applied, the comment will be skipped. If the label doesn't yet exist in the repository, it will be created.

**Comment by jeffhandley** [comment]
This is now enabled in the dotnet/runtime repository with the label `needs-area-label`. Verified here:
https://github.com/dotnet/runtime/issues/82278

There's actually no feasible way to automatically remove the `needs-area-label` label when an `area-` label is applied. That could potentially be a new feature of `issue-labeler`, but we'd need it to additionally respond to `labeled` events and implement the logic itself. In the absence of that automation though, we humans who review/triage the `needs-area-label` label will remove that label when we see another area label applied.

I will now follow up with an augmentation to our issue routing via fabricbot to treat `needs-area-label` as a label that @ericstj and I are accountable for reviewing to help route the issues/PRs.

**Comment by jeffhandley** [comment]
This was implemented in #62
