### ISSUE TITLE
Add issue-labeler for dotnet/dotnet-api-docs

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/issue-labeler#4]
cc: @carlossanlop

**Comment by maryamariyan** [comment]
Update: There's around 160 issues with area labels on dotnet/dotnet-api-docs. I have a model with about 60% accuracy. 

---
For the last 10% of the data (from 16), it guessed 2 wrong:

Predicted: area-System.Reflection, Actual: area-System.Threading for: dotnet/dotnet-api-docs#4585
Predicted: area-System.Runtime, Actual: area-Infrastructure for: dotnet/dotnet-api-docs#4716

And predicted 12 out of 16, with above 40% accuracy.
--- 

Would you like the bot enabled?

**Comment by carlossanlop** [comment]
> _Predicted: area-System.Reflection, Actual: area-System.Threading for: dotnet/dotnet-api-docs#4585_

Is there a way to know why Reflection was predicted, and not Threading?

> _Predicted: area-System.Runtime, Actual: area-Infrastructure for: dotnet/dotnet-api-docs#4716_

Same question. Should `area-Infrastructure` even be among the possible labels to auto-apply? I think those should probably be manually labeled.

> _I have a model with about 60% accuracy._
> _an area like area-System.Data which has zero issues associated with it, is impossible for the ML model to predict as it has no data to train on._

- What's the accuracy in the dotnet/runtime repo?
- Does it improve automatically just by training it for a longer time with existing issues? If that's the case, then we have lots of additional issues without labels that we can triage. I bet we can find at least one for System.Data.

Also: Does the bot create labels that don't exist, or do we need to create them all? I ask because we haven't created them all, we've been creating them manually as needed when triaging.

**Comment by maryamariyan** [comment]
> Also: Does the bot create labels that don't exist, or do we need to create them all? I ask because we haven't created them all, we've been creating them manually as needed when triaging.

The bot would only predict for those area-* labels that are not only created but have existing closed/open issues linked to them. So then yes, let's add missing labels and add them to the issues we already know should have those labels

**Comment by maryamariyan** [comment]
Tested labeler for dotnet/dotnet-api-docs again:

Downloaded 453 issues and PRs with existing area labels for training.
The report below shows the training of the 90% of issues/PRs helped with predicting the last 10% (ordered by date created):

For issues:
```
        Number of issues tested: 37

        handled correctly: 28
        (includes not labeling issues with confidence lower than threshold. (here 60.00%))


        missed: 4
        (includes items that could be labeled if threshold was lower.)


        remaining: 5
        (those incorrectly labeled)

        Predicted: area-System.Net, Actual:area-Infrastructure, NumFound: 2

                For #4681 was 64.55% confident
                For #4763 was 90.96% confident

        Predicted: area-System.Runtime, Actual:area-System.Security, NumFound: 1

                For #4413 was 62.71% confident

        Predicted: area-System.Runtime, Actual:area-WinForms, NumFound: 1

                For #4435 was 72.33% confident

        Predicted: area-System.Runtime, Actual:area-Infrastructure, NumFound: 1

                For #4716 was 89.04% confident
```

For PRs:
```
Number of PRs tested: 8

        handled correctly: 4
        (includes not labeling issues with confidence lower than threshold. (here 60.00%))


        missed: 0
        (includes items that could be labeled if threshold was lower.)


        remaining: 4
        (those incorrectly labeled)

        Predicted: area-Extensions-Hosting, Actual:area-Extensions-Configuration, NumFound: 1

                For #4924 was 94.58% confident

        Predicted: area-System.Runtime, Actual:area-System.Threading, NumFound: 1

                For #4961 was 99.03% confident

        Predicted: area-Extensions-Hosting, Actual:area-Extensions-Logging, NumFound: 1

                For #4996 was 79.16% confident

        Predicted: area-System.Runtime, Actual:area-System.Runtime.InteropServices, NumFound: 1

                For #5042 was 91.72% confident
```

**Comment by maryamariyan** [comment]
closing issue, as the labeler is enabled on the repo now.

**Comment by carlossanlop** [comment]
Great job! Thank you. It will be very useful.
